### ISSUE TITLE
Hello , where is  the log ? 

### ISSUE THREAD

**Issue by cloudzhong** [shadowsocks/shadowsocks-libev#1735] opened 2017-10-14 11:53 UTC
I want to know who is invoking the server, the client IP.
where can I found the log ?

**Comment by cloudzhong** [comment] 2017-10-16 02:45
Can anyone help ?

**Comment by ningwang747** [comment] 2017-10-16 10:56
/var/log/shadowsocks.log

**Comment by SharerMax** [comment] 2017-10-18 04:02
Duplicate of #842

**Closed** 2017-10-23 02:21 UTC
Labels: question

**Comment by legatoo** [comment] 2017-10-27 10:07
face the same issue. Clone the latest code, build and install following the instructions, everything is fine, works charming, but can not find the log. 
shadowsocks-libev 3.0.1

**Comment by marslo** [comment] 2020-07-17 11:04
check log by `$ docker log -f <ss-libev-image-name>`, example:

```
$ docker logs -f ss-libev 
 2020-07-17 17:48:13 [simple-obfs] INFO: obfuscating enabled
 2020-07-17 17:48:13 INFO: plugin "obfs-server" enabled
 2020-07-17 17:48:13 INFO: UDP relay enabled
 2020-07-17 17:48:13 INFO: initializing ciphers... chacha20-ietf-poly1305
 2020-07-17 17:48:13 INFO: Stream ciphers are insecure, therefore deprecated, and should be almost always avoided.
 2020-07-17 17:48:13 INFO: tcp server listening at 127.0.0.1:42960
 2020-07-17 17:48:13 INFO: udp server listening at 0.0.0.0:9000
```
