### ISSUE TITLE
疑问：为什么要默认关闭端口复用？

### ISSUE THREAD

**Issue by pexcn** [shadowsocks/shadowsocks-libev#1191] opened 2017-02-04 11:12 UTC
为什么要默认关闭它呢？ @madeye @Mygod
开启了它以便启用多实例是否对多核设备具有更佳的性能（均衡负载？）？

**Comment by kimw** [comment] 2017-02-04 19:35
FYI #1172

**Comment by kimw** [comment] 2017-02-05 17:46
@pexcn Have I answer your question? If so, maybe you wish to close this issue.

**Comment by pexcn** [comment] 2017-02-05 19:40
@kimw 在多核心设备上有没有必要启用它呢？

**Comment by kimw** [comment] 2017-02-05 20:44
Of cause you should open it, if you want to maximize the performance as instantiate up to core_count + 1.

**Comment by pexcn** [comment] 2017-02-06 05:37
原来如此，但为什么是实例数 = 核心数 + 1？不是应该是 = 核心数吗？

**Comment by kimw** [comment] 2017-02-06 06:32
In short, it's depending on experience， or you should say statistics.

A little bit long story - As you known, a instance will not run at top all the time. Which means, in fact, you could start instance as many as you wishes, even 2 times or 3 times of core numbers. Only the problem is - more instances means more resources it'll take. total core + 1 is a reasonable number.

The full story ... it's a new book, or maybe two books, I plan to write in 2117 A.D. :)

**Closed** 2017-02-06 06:57 UTC
