### ISSUE TITLE
经试验，libev已被检测

### ISSUE THREAD

**Issue by Galaxy0419** [shadowsocks/shadowsocks-libev#1571] opened 2017-07-19 05:24 UTC
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.7

### What operating system are you using?
Debian9 x86

### What did you do?
正常开启服务端或客户端(附加参数：-a nobody --reuse-port)

### What did you expect to see?
速度正常，访问正常

### What did you see instead?
之前使用libev作为服务端一开始正常，后来每次出现一开始速度快后来很慢的现象，今天将libev版作为客户端作本地代理，手机连上出现无法执行次此操作，但是使用手机版shadowsocks可以正常访问。

### What is your config in detail (with all sensitive info masked)?
{
    "server":"my_server_ip",
    "server_port":443,
    "local_address": ”0.0.0.0",
    "local_port":23333,
    "password":"mypassword",
    "timeout":300,
    "method":"chacha20",
    "fast_open": false
}

**Comment by Galaxy0419** [comment] 2017-07-19 05:25
但是使用shadowsocks-go部署服务端速度稳定！

**Comment by chenhw2** [comment] 2017-07-19 05:36
```shadowsocks-android``` using ```shadowsocks-libev```

**Comment by Galaxy0419** [comment] 2017-07-19 07:34
@chenhw2 作为本地代理和本机代理不一样，说明ss-local作本地代理有漏洞

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hillwoodroc** [comment] 2017-07-20 01:27
服务器端开 bbr 了吗？

**Comment by genius001** [comment] 2017-07-20 01:41
from your description can not be sure libev be detected by gfw.

**Comment by steveshi** [comment] 2017-07-20 03:19
不是能不能复现的问题，现在确实已经被检测出来了

**Comment by Galaxy0419** [comment] 2017-07-20 06:41
@hillwoodroc 开了

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Mr-indescribable** [comment] 2017-07-20 06:41
You can testout the new encrypt methods such as chacha20-ietf-poly1305, aes-256-gcm etc...
If you have confirmed that your server has been identified as a shadowsocks server by GFW, you may need a new IP address.

**Comment by madeye** [comment] 2017-07-20 06:58
Unless you provide the traceroute results, no one can help you further.

**Comment by Galaxy0419** [comment] 2017-07-20 07:39
@Mr-indescribable the same

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment] 2017-07-20 07:41
@madeye gfw 最近已经被强化，尤其今天开始打量探测活动已经进行，一下是shadowsocks-go日志
2017/07/20 03:34:34 error getting request 101.85.60.59:35362 67.209.178.39:80 verify one time auth failed, iv=[250 249 198 3 129 137 162 134 75 163 128 50 207 50 102 161] key=[211 244 94 188 233 219 235 76 61 93 34 116 221 226 137 122] data=[244 181 238 40 41 232 204 44 21 194 9 109 195 152 138 73 18 110 95]
2017/07/20 03:34:34 error getting request 101.85.60.59:35365 67.209.178.39:80 addr type 0 not supported
2017/07/20 03:34:34 error getting request 101.85.60.59:35364 67.209.178.39:80 addr type 7 not supported
2017/07/20 03:34:38 error getting request 101.85.60.59:35372 67.209.178.39:80 addr type 12 not supported
2017/07/20 03:34:38 error getting request 101.85.60.59:35373 67.209.178.39:80 addr type 5 not supported
2017/07/20 03:34:38 error getting request 101.85.60.59:35375 67.209.178.39:80 verify one time auth failed, iv=[142 55 106 251 210 30 29 137 150 186 8 17 208 14 176 130] key=[211 244 94 188 233 219 235 76 61 93 34 116 221 226 137 122] data=[20 24 164 42 255 250 27 237 10 51 249 137 215 198 246 237 2 111 177]
2017/07/20 03:34:38 error getting request 101.85.60.59:35371 67.209.178.39:80 addr type 13 not supported
2017/07/20 03:34:38 error getting request 101.85.60.59:35377 67.209.178.39:80 addr type 5 not supported
2017/07/20 03:34:41 error connecting to: 8.93.85.238:5385 dial tcp 8.93.85.238:5385: getsockopt: connection timed out
2017/07/20 03:35:25 error getting request 101.85.60.59:35389 67.209.178.39:80 addr type 14 not supported
2017/07/20 03:35:25 error getting request 101.85.60.59:35388 67.209.178.39:80 addr type 14 not supported
2017/07/20 03:35:25 error getting request 101.85.60.59:35394 67.209.178.39:80 addr type 0 not supported
2017/07/20 03:35:25 error connecting to: �,�Ks:24006 dial tcp: lookup �,�Ks: no such host
2017/07/20 03:35:27 error getting request 101.85.60.59:35399 67.209.178.39:80 addr type 9 not supported
2017/07/20 03:35:27 error getting request 101.85.60.59:35393 67.209.178.39:80 unexpected EOF

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment] 2017-07-20 07:47
@madeye the traceroute result：
1?: [LOCALHOST]                      pmtu 1492
 1:  192.168.0.1                                           3.113ms
 1:  192.168.0.1                                           2.108ms
 2:  192.168.1.1                                           2.882ms
 3:  101.85.60.1                                          16.040ms
 4:  124.74.122.13                                        18.508ms
 5:  124.74.211.177                                       10.855ms
 6:  101.95.120.158                                       12.139ms
 7:  202.97.35.154                                        22.668ms
 8:  202.97.90.29                                         17.271ms
 9:  202.97.63.42                                        143.055ms
10:  203.14.186.206                                      161.761ms
11:  203.14.190.17                                       165.945ms asymm 10
12:  218.30.44.118                                       147.404ms
13:  colo-lax13.as8100.net                               142.981ms asymm 14
14:  192.161.173.82.static.quadranet.com                 164.242ms asymm 15
15:  no reply
16:  no reply
17:  no reply
18:  no reply
19:  no reply
20:  no reply
21:  no reply
22:  no reply
23:  no reply
24:  no reply
25:  no reply
26:  no reply
27:  no reply
28:  no reply
29:  no reply
30:  no reply
     Too many hops: pmtu 1492
     Resume: pmtu 1492

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment] 2017-07-20 08:10
还有一个很奇怪的现象，shadowsocks go虽然显示了大量数据包修改日志但是速度却依旧稳定,是不是因为对待篡改数据行为的不同导致了一些特征产生？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madeye** [comment] 2017-07-20 08:26
1. The traceroute shows no issue with your connection.
2. The shadowsocks-go log shows you're running the service at port 80. It's expected that there are many requests from web spiders or port scanners.

Neither of the above truth is related to packet sniffer or blocking

**Comment by madeye** [comment] 2017-07-20 08:47
From your shadowsocks-go's logs, `101.85.60.59` looks your own IP and keeps connecting to the server with an incorrect cipher or password.

With shadowsocks-libev, this behavior would get the IP blocked. It explains why you saw blocked when using shadowsocks.

**Comment by Galaxy0419** [comment] 2017-07-20 08:58
@madeye 加密和密码没有输入错误，shadowsocks-go的addr type not supported难道不是因为数据包被修改?

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madeye** [comment] 2017-07-20 09:01
@Galaxy0419 Of course not. The log means you have a shadowsocks client using incorrect password or cipher in your LAN.

**Comment by Galaxy0419** [comment] 2017-07-20 09:08
@madeye 但是都是在加密和密码正确的情况下间接出现，而且是可以连通的情况下,顺便请教shadowsocks-libev现在还是出现速度突然下降情况(非80和443端口)，服务端日志只有server recv: Connection timed out

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madeye** [comment] 2017-07-20 09:14
Try port 80 and 443.

**Comment by lixingcong** [comment] 2017-07-20 09:14
我是QN机房，没发现掉速

**Comment by Galaxy0419** [comment] 2017-07-20 09:57
@madeye 测试结果相同

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hikkikuma1991** [comment] 2017-07-21 01:21
心疼Madeye每天除了写代码还要做客服。。ಥ_ಥ

**Comment by Galaxy0419** [comment] 2017-07-21 03:48
今天测试libev版速度最快不超过500kb了，而go版正常！

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment] 2017-07-21 03:48
今天测试libev版速度最快不超过500kb了，而go版正常！

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment] 2017-07-21 03:50
服务器端大量出现并且只出现server recv: Connection timed out

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by blakejia** [comment] 2017-07-21 07:13
你是不是机器已经被盯上了？

**Comment by Robert-Tian** [comment] 2017-07-21 07:27
服务器端大量出现并且只出现server recv: Connection timed out
    "time out" from where? Client or Web Server?

**Comment by xcjiang** [comment] 2017-07-21 08:19
人都进去了，现在还在争论是不是能被检测？ 尽快完善obfs才是正道。

**Comment by Galaxy0419** [comment] 2017-07-21 08:59
@blakejia 不可能，ssh正常登录，而且traceroute也显示没有问题

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment] 2017-07-21 09:00
@xcjiang 谁？madeye？

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Galaxy0419** [comment] 2017-07-21 09:01
@Robert-Tian server revive！

_Sent from my Xiaomi MI 5 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by madeye** [comment] 2017-07-21 10:02
Since it's a timeout of your server, it has nothing to do with shadowsocks itself. Try the following things:

1. Add `-d 8.8.8.8` to your server's command line.
2. Try other implementations, if you really think this could help to improve your performance.

As the issue is already off-topic and the requester cannot provide any useful information, closing the bug.

**Closed by madeye** 2017-07-21 10:02 UTC
Labels: cannot reproduce
