### ISSUE TITLE
Consider solving problems around dependency libraries

### ISSUE THREAD

**Issue by hosiet** [shadowsocks/shadowsocks-libev#1198] opened 2017-02-05 06:26 UTC
Current situation around library dependency is just a mess. Removing vendor libraries (libsodium) and using latest features of libsodium effectively made ss-libev unsuitable for Ubuntu 16.04 and lower. Removing support for OpenSSL made this package unsuitable for Ubuntu 15.10 or lower.

This situation led to various people building and installing libsodium and mbedtls from source code and install them into `/usr`, which is really not a good choice. Manually installed libraries will override system libraries and cause unexpected behaviour to those system programs that were linked against old libraries. What's more, upgrades for libraries from distrubution will overwrite manually-installed libraries, which will make ss-libev unusable after that upgrade.

To solve those problems, I suggest we find a real solution. AFAIK the following options are available:

1. Declare ss-libev 3.x only suitable for Ubuntu 16.10+ and Debian 9+. Users of earlier systems will either solve problems by themselves, or wait for developers from distribution to do backports (Backporter exists for Debian (@rogers0) but no one is backporting ss-libev for Ubuntu now.)

2. Keep compatibility for at least Ubuntu 16.04 LTS by vendoring libsodium code (either use another git submodule or something like copy-paste). Still I recommend dropping support for Ubuntu 15.10 or lower systems, including 14.04 LTS.

3. Vendor all libraries like before (we could use git submodule though to keep codebase clean), and modify build system to provide with independent options for using system libraries or not (Using system library means dynamic linking, and not using system library means static linking. Options could be like `configure --with-system-libsodium --without-system-libcorkipset`). Users who want to compile by themselves can make everything static if they want to, and maintainers from distribution can make every library dynamically linked to meet their needs.

4. Keep current situation.

Any ideas?

**Comment by madeye** [comment] 2017-02-05 06:48
The good news is after https://github.com/shadowsocks/shadowsocks-libev/tree/sip006 merged, the dpendency of libsodium will come back to 1.0.8. 

So, Option 2 looks good to me. Let's declare shadowsocks-libev 3.x only works on Ubuntu 16.04+ and Debian 8+.

**Comment by hosiet** [comment] 2017-02-05 09:39
OK. Let's re-analyze codebase status after that branch get merged.

**Comment by debiansid** [comment] 2017-02-05 11:08
We need 3.0 working on ubuntu 14 please

**Comment by testcaoy7** [comment] 2017-02-05 12:38
If I uninstall libsodium-dev and install latest libsodium, can ss-libev be ran under Ubuntu 14.04 LTS ?

**Comment by madeye** [comment] 2017-02-05 12:48
If your manually built libraries are installed in /usr/local and all environment variables are set properly, then everything should work fine on any distribution.

**Comment by kimw** [comment] 2017-02-05 17:39
Because the Ubuntu 14.04 is still in LTS for about 2 years future, many lowend VPS provider will only support 14.04 for years. So I suggest support 14.04, which is in LTS, for 2 years more.

(5 years LTS, start from 2014, ending to April 2019, see: https://wiki.ubuntu.com/LTS)

![](https://wiki.ubuntu.com/LTS?action=AttachFile&do=get&target=ubuntu-release-cycle-2.png)

**Comment by hosiet** [comment] 2017-02-06 00:06
Ubuntu LTS doesn't necessarily mean dev version must support it. If users of 14.04 really need to use ss-libev, he/she may use older 2.x versions (before 9d99d844) or solve problems by themselves (which is still possible).

**Comment by kimw** [comment] 2017-02-06 00:40
>  If users of 14.04 really need to use ss-libev, he/she may use older 2.x versions

I totally agree with you if ss-libev is a business project just like others do. A rolling upgrade project, in my mind, should keep features all usable.

> solve problems themselves

Sadly, as a non-tech-guy, I can't solve the problems by my hands. Maybe the problem is very easy, but all I can do is just pray like most users do. What I want to say is, I'm not trying to stop the improving of ss-libev, maybe there will a new guy take hand of the old branch, but the community must be separated (you know, kind of same alike issues, features...will be handled in every branch. most importantly, the users will be separated).

**Comment by hosiet** [comment] 2017-02-06 00:49
Then let's see. As per madeye's previous comment, I will work to make the src works on 16.04 LTS at least.

**Comment by madeye** [comment] 2017-02-06 00:49
Not supported doesn't mean not working. Actually, you can build shadowsocks-libev easily on any distribution with all the dependencies installed properly.

What we plan to drop here is building Debian package on old Debian and Ubuntu releases. If you're building shadowsocks-libev from source code, nothing will change.

**Comment by kimw** [comment] 2017-02-06 01:06
> What we plan to drop here is building Debian package on old Debian and Ubuntu releases. If you're building shadowsocks-libev from source code, nothing will change.

cheers!

---

@madeye Why not link libs as static? So there's no need to build the libs separately.

**Comment by madeye** [comment] 2017-02-06 01:19
@kimw It depends. If you're going to release a package for distributions like Debian and OpenWRT, dynamic link is always preferred.

**Comment by cokebar** [comment] 2017-02-06 01:48
@madeye What about mbedtls? In Ubuntu 16.04 LTS, libmbedtls is v2.2.1, is it compatible with shadowsocks-libev 3.X?

**Comment by madeye** [comment] 2017-02-06 01:49
@cokebar Yes, it's compatible.

**Comment by kimw** [comment] 2017-02-06 01:56
@madeye How can I link libsodium as static into ss-libev? Is it that I can keep libsodium 1.0.8-5 (older than v1.0.11) installed from ubuntu package repository and both ss-libev together in one OS?

**Comment by cokebar** [comment] 2017-02-06 01:58
@medeye Good. I think you can declare that for Ubuntu 16.04+, people can install libsodium-dev, libmbedtls-dev directly from repository. And for 15.10 and lower, people should build and install them from source.

**Comment by kimw** [comment] 2017-02-06 02:02
@cokebar libsodium-dev is not compatible with ss-libev v3, which version is 1.0.8, meanwhile < 1.0.11.

**Comment by cokebar** [comment] 2017-02-06 02:24
@kimw see https://github.com/shadowsocks/shadowsocks-libev/issues/1198#issuecomment-277501192

**Closed** 2017-02-08 09:18 UTC
