### ISSUE TITLE
用build_deb.sh编译生成的deb版本3.0.6+ds-1~exp1，不是3.0.7

### ISSUE THREAD

**Issue by c1024** [shadowsocks/shadowsocks-libev#1589] opened 2017-07-25 12:07 UTC
Please answer these questions before submitting your issue. Thanks!

(Please mention that if the issue you filed is solved, you may wish to close it by yourself. Thanks again.)

(PS, you can remove 3 lines above, including this one, before post your issue.)

### What version of shadowsocks-libev are you using?
3.0.6

### What operating system are you using?
debian 8

### What did you do?
用build_deb.sh编译生成deb

### What did you expect to see?
用build_deb.sh编译生成版本3.0.7的deb版本

### What did you see instead?
用build_deb.sh编译生成的deb版本是3.0.6+ds-1~exp1，不是3.0.7

**Comment by rogers0** [comment] 2017-07-25 15:57
@c1024 thanks for your report!
I'll try to fix it this week. Sorry for keeping you waiting.

**Comment by rogers0** [comment] 2017-07-27 12:01
@c1024 I cannot reproduce your result.
Please try again in a clean environment.

**Comment by c1024** [comment] 2017-07-27 14:41
@rogers0 I am sorry to waste you time 。I found it is my problem. I didn't delete old result in the build_area dir.

**Comment by rogers0** [comment] 2017-07-27 16:16
@c1024 Glad to hear that your problem gets resolved.
Please close this issue.

**Closed** 2017-07-27 18:08 UTC
